In [23]:
# Import Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [3]:
# Upload Dataset
df = pd.read_csv('Record.csv')
df

        ID   Age Gender          Grade Result
0        1  18.0  Other    High School   Good
1        2  18.0  Other    High School   Good
2        3  22.0   Male    High School   Good
3        4  17.0  Other    High School   Poor
4        5   NaN  Other    High School   Good
...    ...   ...    ...            ...    ...
4995  4996  20.0  Other  Undergraduate   Good
4996  4997  24.0   Male    High School   Poor
4997  4998  22.0   Male  Undergraduate   Good
4998  4999  17.0   Male  Undergraduate   Good
4999  5000  22.0  Other  Undergraduate   Good

[5000 rows x 5 columns]

In [4]:
# Remove the column which is not required
df.drop(columns = ['ID'],inplace = True)
df.head()

    Age Gender        Grade Result
0  18.0  Other  High School   Good
1  18.0  Other  High School   Good
2  22.0   Male  High School   Good
3  17.0  Other  High School   Poor
4   NaN  Other  High School   Good

In [5]:
# Train and split dataset
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Result']), df['Result'], test_size=0.2, random_state=42)

In [6]:
X_train.head()

       Age  Gender        Grade
4227  23.0  Female  High School
4676  23.0   Other  High School
800   18.0   Other  High School
3671  20.0    Male  High School
4193  17.0   Other  High School

In [7]:
X_train.shape

(4000, 3)

In [8]:
y_train

4227    Average
4676    Average
800        Poor
3671       Good
4193       Poor
         ...
4426       Poor
466     Average
3092       Poor
3772       Poor
860        Poor
Name: Result, Length: 4000, dtype: object

In [9]:
y_train.shape

(4000,)

In [10]:
# See if there is any missing data
df.isnull().sum()

Age       6
Gender    0
Grade     0
Result    0
dtype: int64

In [11]:
# Apply smple imputer to Age to compensate missing value
si_Age = SimpleImputer()
X_train_Age = si_Age.fit_transform(X_train[['Age']])
X_test_Age = si_Age.transform(X_test[['Age']])
X_train_Age

array([[23.],
       [23.],
       [18.],
       ...,
       [17.],
       [21.],
       [18.]], shape=(4000, 1))

In [12]:
X_test_Age

array([[21.       ],
       [22.       ],
       [23.       ],
       [20.       ],
       [19.       ],
       [16.       ],
       [18.       ],
       [22.       ],
       [17.       ],
       [20.       ],
       [19.       ],
       [19.       ],
       [23.       ],
       [20.       ],
       [23.       ],
       [24.       ],
       [23.       ],
       [18.       ],
       [22.       ],
       [24.       ],
       [18.       ],
       [23.       ],
       [18.       ],
       [23.       ],
       [18.       ],
       [22.       ],
       [16.       ],
       [21.       ],
       [19.       ],
       [18.       ],
       [20.       ],
       [25.       ],
       [24.       ],
       [23.       ],
       [19.       ],
       [16.       ],
       [16.       ],
       [17.       ],
       [19.       ],
       [23.       ],
       [16.       ],
       [22.       ],
       [23.       ],
       [17.       ],
       [19.       ],
       [24.       ],
       [24.       ],
       [19.       ],
       [23.       ],
       [18.       ],
       [20.       ],
       [16.       ],
       [23.       ],
       [20.       ],
       [21.       ],
       [20.       ],
       [20.       ],
       [19.       ],
       [18.       ],
       [17.       ],
       [17.       ],
       [17.       ],
       [23.       ],
       [21.       ],
       [20.       ],
       [25.       ],
       [16.       ],
       [24.       ],
       [16.       ],
       [24.       ],
       [16.       ],
       [24.       ],
       [20.       ],
       [16.       ],
       [17.       ],
       [16.       ],
       [16.       ],
       [23.       ],
       [19.       ],
       [16.       ],
       [25.       ],
       [21.       ],
       [21.       ],
       [21.       ],
       [24.       ],
       [18.       ],
       [22.       ],
       [25.       ],
       [19.       ],
       [20.       ],
       [24.       ],
       [17.       ],
       [18.       ],
       [23.       ],
       [24.       ],
       [22.       ],
       [25.       ],
       [18.       ],
       [21.       ],
       [25.       ],
       [24.       ],
       [24.       ],
       [16.       ],
       [20.       ],
       [25.       ],
       [23.       ],
       [25.       ],
       [18.       ],
       [25.       ],
       [25.       ],
       [19.       ],
       [20.       ],
       [23.       ],
       [25.       ],
       [16.       ],
       [23.       ],
       [24.       ],
       [18.       ],
       [24.       ],
       [18.       ],
       [19.       ],
       [17.       ],
       [18.       ],
       [25.       ],
       [16.       ],
       [25.       ],
       [17.       ],
       [25.       ],
       [20.       ],
       [16.       ],
       [22.       ],
       [19.       ],
       [20.       ],
       [18.       ],
       [23.       ],
       [25.       ],
       [23.       ],
       [20.       ],
       [18.       ],
       [16.       ],
       [18.       ],
       [20.       ],
       [24.       ],
       [16.       ],
       [24.       ],
       [24.       ],
       [17.       ],
       [19.       ],
       [22.       ],
       [19.       ],
       [25.       ],
       [24.       ],
       [19.       ],
       [25.       ],
       [24.       ],
       [16.       ],
       [17.       ],
       [23.       ],
       [21.       ],
       [17.       ],
       [17.       ],
       [25.       ],
       [25.       ],
       [25.       ],
       [18.       ],
       [23.       ],
       [18.       ],
       [22.       ],
       [24.       ],
       [24.       ],
       [19.       ],
       [23.       ],
       [18.       ],
       [19.       ],
       [25.       ],
       [22.       ],
       [22.       ],
       [23.       ],
       [19.       ],
       [16.       ],
       [21.       ],
       [23.       ],
       [16.       ],
       [21.       ],
       [24.       ],
       [20.       ],
       [25.       ],
       [20.       ],
       [25.       ],
       [17.       ],
       [23.       ],
       [25.       ],
       [19.       ],
       [23.       ],
       [17.       ],
       [24.       ],
       [24.       ],
       [22.       ],
       [18.       ],
       [18.       ],
       [19.       ],
       [23.       ],
       [19.       ],
       [25.       ],
       [16.       ],
       [24.       ],
       [21.       ],
       [23.       ],
       [22.       ],
       [16.       ],
       [25.       ],
       [21.       ],
       [17.       ],
       [17.       ],
       [20.       ],
       [25.       ],
       [17.       ],
       [22.       ],
       [20.       ],
       [23.       ],
       [16.       ],
       [16.       ],
       [20.       ],
       [22.       ],
       [18.       ],
       [18.       ],
       [16.       ],
       [18.       ],
       [16.       ],
       [20.       ],
       [19.       ],
       [23.       ],
       [16.       ],
       [23.       ],
       [17.       ],
       [16.       ],
       [20.       ],
       [24.       ],
       [21.       ],
       [24.       ],
       [23.       ],
       [16.       ],
       [16.       ],
       [17.       ],
       [19.       ],
       [19.       ],
       [17.       ],
       [20.       ],
       [16.       ],
       [25.       ],
       [17.       ],
       [20.       ],
       [17.       ],
       [19.       ],
       [20.       ],
       [21.       ],
       [20.       ],
       [18.       ],
       [23.       ],
       [22.       ],
       [24.       ],
       [18.       ],
       [22.       ],
       [20.       ],
       [24.       ],
       [22.       ],
       [23.       ],
       [18.       ],
       [18.       ],
       [21.       ],
       [18.       ],
       [19.       ],
       [21.       ],
       [16.       ],
       [19.       ],
       [20.       ],
       [19.       ],
       [22.       ],
       [19.       ],
       [22.       ],
       [20.       ],
       [19.       ],
       [18.       ],
       [21.       ],
       [16.       ],
       [16.       ],
       [16.       ],
       [17.       ],
       [23.       ],
       [17.       ],
       [18.       ],
       [19.       ],
       [24.       ],
       [19.       ],
       [23.       ],
       [22.       ],
       [24.       ],
       [24.       ],
       [21.       ],
       [17.       ],
       [17.       ],
       [24.       ],
       [19.       ],
       [16.       ],
       [19.       ],
       [17.       ],
       [25.       ],
       [22.       ],
       [23.       ],
       [24.       ],
       [25.       ],
       [17.       ],
       [21.       ],
       [17.       ],
       [18.       ],
       [17.       ],
       [18.       ],
       [23.       ],
       [18.       ],
       [21.       ],
       [23.       ],
       [19.       ],
       [25.       ],
       [24.       ],
       [22.       ],
       [21.       ],
       [16.       ],
       [16.       ],
       [20.       ],
       [23.       ],
       [24.       ],
       [22.       ],
       [23.       ],
       [25.       ],
       [22.       ],
       [19.       ],
       [16.       ],
       [22.       ],
       [21.       ],
       [24.       ],
       [19.       ],
       [19.       ],
       [17.       ],
       [24.       ],
       [22.       ],
       [24.       ],
       [25.       ],
       [22.       ],
       [18.       ],
       [23.       ],
       [21.       ],
       [19.       ],
       [16.       ],
       [16.       ],
       [25.       ],
       [23.       ],
       [25.       ],
       [25.       ],
       [24.       ],
       [17.       ],
       [20.       ],
       [25.       ],
       [24.       ],
       [20.       ],
       [17.       ],
       [20.       ],
       [20.       ],
       [16.       ],
       [25.       ],
       [24.       ],
       [20.       ],
       [19.       ],
       [22.       ],
       [23.       ],
       [19.       ],
       [16.       ],
       [24.       ],
       [19.       ],
       [21.       ],
       [20.       ],
       [16.       ],
       [21.       ],
       [22.       ],
       [24.       ],
       [19.       ],
       [22.       ],
       [20.       ],
       [24.       ],
       [25.       ],
       [25.       ],
       [21.       ],
       [23.       ],
       [19.       ],
       [25.       ],
       [23.       ],
       [19.       ],
       [19.       ],
       [17.       ],
       [19.       ],
       [25.       ],
       [17.       ],
       [23.       ],
       [25.       ],
       [18.       ],
       [24.       ],
       [17.       ],
       [16.       ],
       [19.       ],
       [25.       ],
       [21.       ],
       [25.       ],
       [18.       ],
       [24.       ],
       [25.       ],
       [19.       ],
       [21.       ],
       [19.       ],
       [20.       ],
       [23.       ],
       [25.       ],
       [16.       ],
       [21.       ],
       [16.       ],
       [25.       ],
       [24.       ],
       [21.       ],
       [18.       ],
       [17.       ],
       [24.       ],
       [19.       ],
       [21.       ],
       [22.       ],
       [19.       ],
       [21.       ],
       [17.       ],
       [21.       ],
       [19.       ],
       [18.       ],
       [20.       ],
       [25.       ],
       [17.       ],
       [20.5068836],
       [21.       ],
       [20.       ],
       [24.       ],
       [18.       ],
       [23.       ],
       [21.       ],
       [20.       ],
       [22.       ],
       [16.       ],
       [22.       ],
       [18.       ],
       [24.       ],
       [24.       ],
       [22.       ],
       [22.       ],
       [16.       ],
       [19.       ],
       [22.       ],
       [24.       ],
       [18.       ],
       [17.       ],
       [20.       ],
       [22.       ],
       [25.       ],
       [22.       ],
       [25.       ],
       [24.       ],
       [24.       ],
       [23.       ],
       [19.       ],
       [24.       ],
       [17.       ],
       [17.       ],
       [20.       ],
       [23.       ],
       [16.       ],
       [22.       ],
       [24.       ],
       [19.       ],
       [22.       ],
       [18.       ],
       [23.       ],
       [24.       ],
       [19.       ],
       [18.       ],
       [19.       ],
       [23.       ],
       [19.       ],
       [24.       ],
       [16.       ],
       [25.       ],
       [17.       ],
       [24.       ],
       [21.       ],
       [24.       ],
       [16.       ],
       [22.       ],
       [21.       ],
       [22.       ],
       [20.       ],
       [23.       ],
       [20.       ],
       [22.       ],
       [20.       ],
       [25.       ],
       [22.       ],
       [23.       ],
       [22.       ],
       [23.       ],
       [16.       ],
       [22.       ],
       [20.       ],
       [20.       ],
       [23.       ],
       [16.       ],
       [19.       ],
       [25.       ],
       [20.       ],
       [25.       ],
       [24.       ],
       [23.       ],
       [21.       ],
       [19.       ],
       [16.       ],
       [21.       ],
       [19.       ],
       [16.       ],
       [16.       ],
       [22.       ],
       [20.       ],
       [19.       ],
       [22.       ],
       [22.       ],
       [23.       ],
       [20.       ],
       [17.       ],
       [24.       ],
       [16.       ],
       [22.       ],
       [17.       ],
       [22.       ],
       [19.       ],
       [16.       ],
       [24.       ],
       [16.       ],
       [20.       ],
       [23.       ],
       [22.       ],
       [22.       ],
       [16.       ],
       [18.       ],
       [17.       ],
       [16.       ],
       [24.       ],
       [18.       ],
       [23.       ],
       [18.       ],
       [23.       ],
       [21.       ],
       [25.       ],
       [17.       ],
       [18.       ],
       [16.       ],
       [25.       ],
       [23.       ],
       [21.       ],
       [19.       ],
       [22.       ],
       [22.       ],
       [23.       ],
       [21.       ],
       [22.       ],
       [16.       ],
       [17.       ],
       [25.       ],
       [16.       ],
       [21.       ],
       [19.       ],
       [16.       ],
       [20.       ],
       [25.       ],
       [16.       ],
       [18.       ],
       [24.       ],
       [18.       ],
       [25.       ],
       [23.       ],
       [24.       ],
       [22.       ],
       [20.       ],
       [17.       ],
       [21.       ],
       [25.       ],
       [22.       ],
       [23.       ],
       [24.       ],
       [18.       ],
       [16.       ],
       [18.       ],
       [23.       ],
       [17.       ],
       [25.       ],
       [23.       ],
       [25.       ],
       [23.       ],
       [20.       ],
       [19.       ],
       [17.       ],
       [21.       ],
       [20.       ],
       [24.       ],
       [24.       ],
       [20.       ],
       [20.       ],
       [20.       ],
       [16.       ],
       [16.       ],
       [21.       ],
       [20.       ],
       [25.       ],
       [22.       ],
       [17.       ],
       [25.       ],
       [18.       ],
       [18.       ],
       [24.       ],
       [24.       ],
       [21.       ],
       [24.       ],
       [19.       ],
       [16.       ],
       [22.       ],
       [17.       ],
       [19.       ],
       [21.       ],
       [16.       ],
       [24.       ],
       [21.       ],
       [22.       ],
       [25.       ],
       [21.       ],
       [18.       ],
       [24.       ],
       [25.       ],
       [18.       ],
       [25.       ],
       [17.       ],
       [20.       ],
       [25.       ],
       [17.       ],
       [20.       ],
       [24.       ],
       [17.       ],
       [20.       ],
       [25.       ],
       [23.       ],
       [24.       ],
       [24.       ],
       [25.       ],
       [22.       ],
       [19.       ],
       [24.       ],
       [25.       ],
       [17.       ],
       [25.       ],
       [18.       ],
       [19.       ],
       [23.       ],
       [22.       ],
       [21.       ],
       [19.       ],
       [20.       ],
       [16.       ],
       [20.       ],
       [22.       ],
       [25.       ],
       [16.       ],
       [23.       ],
       [21.       ],
       [22.       ],
       [21.       ],
       [24.       ],
       [18.       ],
       [22.       ],
       [22.       ],
       [19.       ],
       [19.       ],
       [18.       ],
       [22.       ],
       [20.       ],
       [24.       ],
       [22.       ],
       [21.       ],
       [25.       ],
       [17.       ],
       [21.       ],
       [21.       ],
       [24.       ],
       [16.       ],
       [23.       ],
       [16.       ],
       [21.       ],
       [24.       ],
       [23.       ],
       [23.       ],
       [18.       ],
       [20.       ],
       [19.       ],
       [18.       ],
       [18.       ],
       [20.       ],
       [25.       ],
       [22.       ],
       [23.       ],
       [17.       ],
       [16.       ],
       [20.       ],
       [24.       ],
       [17.       ],
       [20.       ],
       [16.       ],
       [24.       ],
       [25.       ],
       [20.       ],
       [22.       ],
       [25.       ],
       [21.       ],
       [21.       ],
       [21.       ],
       [23.       ],
       [25.       ],
       [17.       ],
       [21.       ],
       [23.       ],
       [20.       ],
       [16.       ],
       [20.       ],
       [21.       ],
       [20.       ],
       [22.       ],
       [20.       ],
       [25.       ],
       [16.       ],
       [21.       ],
       [16.       ],
       [19.       ],
       [20.       ],
       [20.       ],
       [18.       ],
       [16.       ],
       [17.       ],
       [17.       ],
       [23.       ],
       [18.       ],
       [25.       ],
       [17.       ],
       [20.       ],
       [21.       ],
       [23.       ],
       [16.       ],
       [23.       ],
       [16.       ],
       [16.       ],
       [20.       ],
       [21.       ],
       [21.       ],
       [21.       ],
       [22.       ],
       [20.       ],
       [24.       ],
       [19.       ],
       [18.       ],
       [20.       ],
       [18.       ],
       [16.       ],
       [19.       ],
       [21.       ],
       [18.       ],
       [19.       ],
       [19.       ],
       [24.       ],
       [16.       ],
       [18.       ],
       [18.       ],
       [21.       ],
       [16.       ],
       [17.       ],
       [20.       ],
       [16.       ],
       [21.       ],
       [24.       ],
       [23.       ],
       [18.       ],
       [24.       ],
       [18.       ],
       [22.       ],
       [23.       ],
       [22.       ],
       [23.       ],
       [20.       ],
       [24.       ],
       [20.       ],
       [25.       ],
       [17.       ],
       [23.       ],
       [22.       ],
       [22.       ],
       [24.       ],
       [25.       ],
       [17.       ],
       [23.       ],
       [24.       ],
       [19.       ],
       [22.       ],
       [24.       ],
       [21.       ],
       [25.       ],
       [23.       ],
       [20.       ],
       [17.       ],
       [24.       ],
       [20.       ],
       [17.       ],
       [20.       ],
       [20.       ],
       [20.       ],
       [25.       ],
       [25.       ],
       [20.       ],
       [20.       ],
       [19.       ],
       [19.       ],
       [17.       ],
       [19.       ],
       [20.       ],
       [25.       ],
       [17.       ],
       [18.       ],
       [18.       ],
       [17.       ],
       [16.       ],
       [23.       ],
       [18.       ],
       [22.       ],
       [22.       ],
       [18.       ],
       [20.       ],
       [22.       ],
       [24.       ],
       [17.       ],
       [23.       ],
       [16.       ],
       [16.       ],
       [25.       ],
       [22.       ],
       [25.       ],
       [21.       ],
       [20.       ],
       [16.       ],
       [16.       ],
       [16.       ],
       [25.       ],
       [20.       ],
       [19.       ],
       [23.       ],
       [24.       ],
       [25.       ],
       [23.       ],
       [16.       ],
       [20.       ],
       [21.       ],
       [20.       ],
       [24.       ],
       [21.       ],
       [16.       ],
       [21.       ],
       [23.       ],
       [21.       ],
       [23.       ],
       [17.       ],
       [17.       ],
       [25.       ],
       [25.       ],
       [22.       ],
       [24.       ],
       [24.       ],
       [23.       ],
       [17.       ],
       [22.       ],
       [16.       ],
       [20.       ],
       [24.       ],
       [18.       ],
       [25.       ],
       [18.       ],
       [17.       ],
       [16.       ],
       [18.       ],
       [22.       ],
       [25.       ],
       [19.       ],
       [18.       ],
       [23.       ],
       [22.       ],
       [21.       ],
       [23.       ],
       [18.       ],
       [18.       ],
       [24.       ],
       [21.       ],
       [20.       ],
       [20.       ],
       [18.       ],
       [24.       ],
       [17.       ],
       [17.       ],
       [20.       ],
       [17.       ],
       [23.       ],
       [21.       ],
       [18.       ],
       [17.       ],
       [21.       ],
       [24.       ],
       [24.       ],
       [22.       ],
       [17.       ],
       [20.       ],
       [21.       ],
       [16.       ],
       [16.       ],
       [17.       ],
       [23.       ],
       [20.       ],
       [25.       ],
       [23.       ],
       [17.       ],
       [18.       ],
       [24.       ],
       [19.       ],
       [25.       ],
       [24.       ],
       [23.       ],
       [18.       ],
       [21.       ],
       [17.       ],
       [23.       ],
       [25.       ],
       [22.       ],
       [18.       ],

In [13]:
# Gender is a nominal category so apply OneHot Encoder
ohe_Gender = OneHotEncoder (sparse_output = False,handle_unknown ='ignore')
X_train_Gender = ohe_Gender.fit_transform(X_train[['Gender']])
X_test_Gender = ohe_Gender.transform(X_test[['Gender']])
X_train_Gender

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]], shape=(4000, 3))

In [14]:
X_test_Gender

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]], shape=(1000, 3))

In [15]:
# Apply Ordinal Encoder to Grade since it is ordinal categorical value
oe_Grade = OrdinalEncoder(categories = [['High School','Undergraduate','Postgraduate']])
X_train_Grade = oe_Grade.fit_transform(X_train[['Grade']])
X_test_Grade = oe_Grade.fit_transform(X_test[['Grade']])
X_train_Grade

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [2.],
       [2.]], shape=(4000, 1))

In [16]:
X_test_Grade

array([[2.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [1.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [1.],
       [2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [2.],
       [1.],
       [2.],
       [2.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [1.],
       [0.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [0.],
       [0.],
       [0.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [0.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [0.],
       [2.],
       [1.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [1.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [1.],
       [2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [1.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [2.],
       [1.],
       [0.],
       [0.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [1.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [2.],
       [1.],
       [2.],
       [2.],
       [1.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [2.],
       [1.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [0.],
       [2.],
       [2.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [0.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [1.],
       [2.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [0.],
       [2.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [0.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [2.],
       [2.],
       [1.],
       [0.],
       [2.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [2.],
       [1.],
       [2.],
       [0.],
       [2.],
       [1.],
       [1.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [2.],
       [1.],
       [2.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [1.],
       [2.],
       [0.],
       [0.],
       [1.],
       [0.],
       [2.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [0.],
       [2.],
       [0.],
       [2.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [2.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [2.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [1.],
       [2.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [1.],
       [0.],
       [2.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [2.],
       [0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [1.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [2.],
       [0.],
       [2.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [1.],
       [2.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [1.],
       [0.],
       [2.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.]])

In [17]:
# Apply Label encoding for Result since it is output feature
le_Result = LabelEncoder()
y_train_Result = le_Result.fit_transform(y_train)
y_test_Result = le_Result.transform(y_test)
y_train_Result

array([0, 0, 2, ..., 2, 2, 2], shape=(4000,))

In [18]:
# Concatenate all values
X_train_new = np.concatenate(( X_train_Age, X_train_Gender, X_train_Grade), axis=1)
# also the test data
X_test_new = np.concatenate((X_test_Age, X_test_Gender, X_test_Grade), axis=1)

X_train_new.shape

(4000, 5)

In [20]:
# Implementation of model
clf = DecisionTreeClassifier()
clf.fit(X_train_new, y_train)

DecisionTreeClassifier()

In [22]:
# Prediction
y_pred = clf.predict(X_test_new)
y_pred

array(['Average', 'Average', 'Poor', 'Average', 'Good', 'Average', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Average', 'Good', 'Good', 'Poor',
       'Poor', 'Poor', 'Poor', 'Good', 'Good', 'Poor', 'Poor', 'Poor',
       'Average', 'Poor', 'Good', 'Good', 'Average', 'Good', 'Poor',
       'Good', 'Good', 'Poor', 'Poor', 'Average', 'Good', 'Average',
       'Average', 'Poor', 'Average', 'Good', 'Good', 'Poor', 'Average',
       'Good', 'Poor', 'Good', 'Good', 'Good', 'Poor', 'Good', 'Average',
       'Good', 'Good', 'Good', 'Good', 'Average', 'Average', 'Good',
       'Average', 'Average', 'Average', 'Poor', 'Average', 'Average',
       'Poor', 'Good', 'Good', 'Average', 'Poor', 'Good', 'Poor',
       'Average', 'Good', 'Poor', 'Good', 'Good', 'Average', 'Good',
       'Good', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Poor', 'Good', 'Poor', 'Average', 'Average',
       'Good', 'Poor', 'Average', 'Poor', 'Average', 'Average', 'Average',
       'Good', 'Good', 'Good', 'Good', 'Poor', 'Good', 'Good', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Poor', 'Poor',
       'Average', 'Average', 'Good', 'Good', 'Poor', 'Average', 'Average',
       'Average', 'Good', 'Good', 'Average', 'Good', 'Good', 'Good',
       'Average', 'Good', 'Good', 'Good', 'Poor', 'Average', 'Good',
       'Poor', 'Good', 'Poor', 'Good', 'Poor', 'Average', 'Poor',
       'Average', 'Poor', 'Average', 'Poor', 'Average', 'Average',
       'Average', 'Poor', 'Good', 'Poor', 'Average', 'Average', 'Good',
       'Good', 'Good', 'Poor', 'Poor', 'Good', 'Average', 'Good', 'Good',
       'Poor', 'Average', 'Average', 'Poor', 'Average', 'Good', 'Good',
       'Average', 'Poor', 'Poor', 'Good', 'Good', 'Average', 'Good',
       'Poor', 'Good', 'Average', 'Good', 'Average', 'Poor', 'Poor',
       'Average', 'Average', 'Average', 'Poor', 'Good', 'Good', 'Good',
       'Average', 'Average', 'Poor', 'Average', 'Good', 'Average',
       'Average', 'Good', 'Good', 'Good', 'Poor', 'Poor', 'Average',
       'Average', 'Good', 'Good', 'Average', 'Poor', 'Poor', 'Good',
       'Good', 'Average', 'Average', 'Poor', 'Poor', 'Average', 'Poor',
       'Poor', 'Poor', 'Good', 'Good', 'Good', 'Poor', 'Average', 'Poor',
       'Poor', 'Average', 'Poor', 'Good', 'Good', 'Poor', 'Poor', 'Good',
       'Poor', 'Average', 'Average', 'Good', 'Average', 'Average',
       'Average', 'Poor', 'Good', 'Good', 'Good', 'Good', 'Poor',
       'Average', 'Good', 'Good', 'Good', 'Good', 'Good', 'Average',
       'Good', 'Average', 'Poor', 'Good', 'Average', 'Poor', 'Average',
       'Average', 'Average', 'Poor', 'Good', 'Average', 'Good', 'Poor',
       'Poor', 'Poor', 'Good', 'Poor', 'Good', 'Average', 'Average',
       'Poor', 'Good', 'Good', 'Good', 'Poor', 'Good', 'Average', 'Poor',
       'Good', 'Good', 'Average', 'Average', 'Average', 'Good', 'Good',
       'Average', 'Good', 'Average', 'Poor', 'Poor', 'Good', 'Good',
       'Poor', 'Average', 'Poor', 'Good', 'Good', 'Poor', 'Poor', 'Good',
       'Poor', 'Good', 'Average', 'Good', 'Average', 'Average', 'Average',
       'Poor', 'Good', 'Good', 'Average', 'Good', 'Poor', 'Poor', 'Poor',
       'Good', 'Poor', 'Average', 'Good', 'Average', 'Poor', 'Average',
       'Average', 'Good', 'Average', 'Good', 'Good', 'Poor', 'Poor',
       'Good', 'Good', 'Poor', 'Good', 'Good', 'Average', 'Average',
       'Average', 'Good', 'Good', 'Average', 'Average', 'Average', 'Good',
       'Poor', 'Good', 'Poor', 'Average', 'Good', 'Good', 'Good',
       'Average', 'Good', 'Good', 'Good', 'Average', 'Average', 'Average',
       'Good', 'Poor', 'Good', 'Average', 'Good', 'Average', 'Average',
       'Good', 'Good', 'Good', 'Average', 'Poor', 'Poor', 'Good',
       'Average', 'Good', 'Good', 'Average', 'Good', 'Poor', 'Poor',
       'Good', 'Good', 'Average', 'Poor', 'Good', 'Average', 'Good',
       'Poor', 'Poor', 'Poor', 'Good', 'Good', 'Average', 'Poor', 'Poor',
       'Average', 'Good', 'Good', 'Good', 'Good', 'Poor', 'Good', 'Poor',
       'Average', 'Good', 'Average', 'Good', 'Average', 'Good', 'Poor',
       'Average', 'Good', 'Poor', 'Average', 'Good', 'Good', 'Poor',
       'Average', 'Good', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Good', 'Average', 'Average', 'Poor', 'Average', 'Good',
       'Good', 'Average', 'Poor', 'Average', 'Poor', 'Average', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Average', 'Poor',
       'Average', 'Average', 'Good', 'Good', 'Poor', 'Good', 'Average',
       'Average', 'Average', 'Good', 'Average', 'Average', 'Good',
       'Average', 'Good', 'Average', 'Average', 'Good', 'Average', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Average', 'Poor', 'Good', 'Poor',
       'Average', 'Poor', 'Good', 'Good', 'Good', 'Good', 'Average',
       'Good', 'Poor', 'Poor', 'Good', 'Average', 'Poor', 'Good', 'Poor',
       'Poor', 'Average', 'Average', 'Average', 'Poor', 'Average', 'Poor',
       'Average', 'Good', 'Good', 'Average', 'Good', 'Poor', 'Average',
       'Poor', 'Average', 'Average', 'Good', 'Poor', 'Good', 'Good',
       'Good', 'Poor', 'Good', 'Good', 'Good', 'Poor', 'Average', 'Good',
       'Average', 'Good', 'Average', 'Good', 'Average', 'Good', 'Good',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Poor',
       'Good', 'Average', 'Average', 'Good', 'Average', 'Average', 'Good',
       'Average', 'Average', 'Good', 'Average', 'Poor', 'Average', 'Good',
       'Good', 'Average', 'Average', 'Poor', 'Good', 'Average', 'Good',
       'Good', 'Average', 'Average', 'Average', 'Good', 'Good', 'Average',
       'Poor', 'Good', 'Good', 'Poor', 'Good', 'Average', 'Poor',
       'Average', 'Good', 'Average', 'Poor', 'Good', 'Good', 'Good',
       'Average', 'Average', 'Good', 'Good', 'Good', 'Average', 'Good',
       'Good', 'Good', 'Good', 'Average', 'Average', 'Average', 'Average',
       'Good', 'Good', 'Average', 'Good', 'Poor', 'Average', 'Good',
       'Good', 'Poor', 'Average', 'Average', 'Average', 'Poor', 'Good',
       'Average', 'Good', 'Poor', 'Good', 'Poor', 'Good', 'Good',
       'Average', 'Good', 'Poor', 'Average', 'Poor', 'Average', 'Poor',
       'Average', 'Good', 'Poor', 'Good', 'Good', 'Average', 'Poor',
       'Poor', 'Average', 'Average', 'Good', 'Good', 'Average', 'Good',
       'Poor', 'Poor', 'Good', 'Poor', 'Good', 'Average', 'Good', 'Good',
       'Average', 'Poor', 'Good', 'Good', 'Poor', 'Average', 'Good',
       'Good', 'Poor', 'Good', 'Average', 'Good', 'Average', 'Average',
       'Good', 'Good', 'Average', 'Average', 'Good', 'Poor', 'Good',
       'Average', 'Average', 'Average', 'Good', 'Average', 'Average',
       'Good', 'Good', 'Good', 'Good', 'Average', 'Good', 'Average',
       'Good', 'Good', 'Average', 'Good', 'Good', 'Good', 'Good',
       'Average', 'Good', 'Good', 'Average', 'Average', 'Poor', 'Average',
       'Average', 'Good', 'Poor', 'Poor', 'Good', 'Good', 'Average',
       'Good', 'Poor', 'Average', 'Good', 'Average', 'Poor', 'Good',
       'Good', 'Poor', 'Good', 'Average', 'Average', 'Average', 'Good',
       'Poor', 'Good', 'Average', 'Good', 'Good', 'Average', 'Average',
       'Average', 'Good', 'Good', 'Average', 'Good', 'Poor', 'Good',
       'Good', 'Average', 'Good', 'Good', 'Good', 'Poor', 'Good',
       'Average', 'Poor', 'Good', 'Poor', 'Average', 'Average', 'Good',
       'Average', 'Average', 'Good', 'Poor', 'Good', 'Good', 'Average',
       'Good', 'Poor', 'Good', 'Average', 'Poor', 'Poor', 'Good', 'Good',
       'Average', 'Average', 'Poor', 'Average', 'Average', 'Poor',
       'Average', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Poor',
       'Good', 'Average', 'Average', 'Average', 'Good', 'Good', 'Good',
       'Good', 'Good', 'Average', 'Good', 'Good', 'Good', 'Poor',
       'Average', 'Good', 'Good', 'Average', 'Average', 'Good', 'Poor',
       'Average', 'Poor', 'Good', 'Poor', 'Average', 'Poor', 'Average',
       'Average', 'Average', 'Poor', 'Average', 'Average', 'Good',
       'Average', 'Average', 'Poor', 'Good', 'Good', 'Good', 'Good',
       'Average', 'Poor', 'Average', 'Average', 'Good', 'Average', 'Good',
       'Poor', 'Average', 'Good', 'Average', 'Good', 'Good', 'Average',
       'Poor', 'Good', 'Average', 'Poor', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Good', 'Average', 'Average',
       'Average', 'Poor', 'Poor', 'Good', 'Good', 'Good', 'Poor', 'Good',
       'Average', 'Good', 'Average', 'Poor', 'Poor', 'Poor', 'Average',
       'Good', 'Poor', 'Average', 'Good', 'Average', 'Good', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Good', 'Good', 'Good',
       'Poor', 'Average', 'Poor', 'Good', 'Good', 'Poor', 'Poor',
       'Average', 'Poor', 'Good', 'Average', 'Average', 'Good', 'Poor',
       'Good', 'Good', 'Average', 'Poor', 'Average', 'Average', 'Good',
       'Good', 'Average', 'Poor', 'Good', 'Good', 'Average', 'Poor',
       'Average', 'Poor', 'Good', 'Poor', 'Average', 'Poor', 'Poor',
       'Poor', 'Good', 'Good', 'Average', 'Poor', 'Good', 'Good', 'Poor',
       'Good', 'Poor', 'Poor', 'Poor', 'Average', 'Average', 'Poor',
       'Average', 'Poor', 'Average', 'Poor', 'Average', 'Poor', 'Good',
       'Good', 'Good', 'Poor', 'Good', 'Good', 'Good', 'Good', 'Poor',
       'Poor', 'Good', 'Good', 'Average', 'Good', 'Average', 'Average',
       'Average', 'Poor', 'Average', 'Average', 'Good', 'Poor', 'Poor',
       'Good', 'Average', 'Average', 'Poor', 'Good', 'Poor', 'Average',
       'Average', 'Poor', 'Average', 'Good', 'Good', 'Average', 'Poor',
       'Average', 'Good', 'Average', 'Poor', 'Average', 'Poor', 'Average',
       'Good', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Good', 'Good', 'Poor', 'Poor', 'Good',
       'Good', 'Average', 'Good', 'Poor', 'Average', 'Good', 'Average',
       'Average', 'Poor', 'Average', 'Good', 'Good', 'Good', 'Average',
       'Good', 'Average', 'Average', 'Average', 'Average', 'Good', 'Poor',
       'Poor', 'Good', 'Average', 'Good', 'Poor'], dtype=object)

In [24]:
#accuracy
accuracy_score(y_pred, y_test)

0.335

In [28]:
# Code for production
import pickle
pickle.dump(ohe_Gender,open('Machine Learning/ohe_Gender.pkl','wb'))
pickle.dump(oe_Grade,open('Machine Learning/oe_Grade.pkl','wb'))
pickle.dump(le_Result,open('Machine Learning/le_Result.pkl','wb'))
pickle.dump(clf,open('Machine Learning/clf.pkl','wb'))